# Generated by Django 5.1.1 on 2024-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_admin', models.BooleanField(default=True, verbose_name='Is admin')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Is staff')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Is superuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
