# Generated by Django 5.1.1 on 2024-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Display name'),
        ),
    ]
